$(document).ready(function(){
    $('.nav-toggle').click(function(){
        $('.nav-toggle').toggleClass('active');
        $('.sidebar').toggleClass('active');
    })

    $('.owl-historia').owlCarousel({
        loop:true,
        margin:10,
        autoplay:true,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        stagePadding:0,
        nav:true,
        responsive:{
            300:{
                items:1,
            }
        }
    });

    $('#initial').click(function(){
        $(this).css('opacity','0');
        setTimeout(function(){
            $('#initial').css('display','none');
            $('footer').attr('style','display:block;');
        },1500);
    });

    $('.owl-equipoHumano').owlCarousel({
        loop:true,
        margin:10,
        autoplay:true,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        stagePadding:0,
        nav:true,
        responsive:{
            300:{
                items:1,
            },
            600:{
                items:2,
            },
            900:{
                items:3,
            }
        }
    });
})